# Generated by Django 5.2.2 on 2025-06-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('is_displayed', models.BooleanField(default=True, verbose_name='Показать')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'ordering': ['order'],
            },
        ),
    ]
