# Generated by Django 5.2.2 on 2025-06-16 09:10

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Наименование')),
                ('is_displayed', models.BooleanField(default=True, verbose_name='Показать')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Желаемая должность',
                'verbose_name_plural': 'Желаемые должности',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Наименование')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Пример, +79510549236', max_length=128, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254)),
                ('github', models.URLField(verbose_name='Ссылка на GITHUB')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vacancy.profession')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
