# Generated by Django 5.2.2 on 2025-06-09 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Наименование')),
                ('is_displayed', models.BooleanField(default=True, verbose_name='Показать')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип проекта',
                'verbose_name_plural': 'Типы проектов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('is_displayed', models.BooleanField(default=True, verbose_name='Показать')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('typeProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.typeproject')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order'],
            },
        ),
    ]
