# Generated by Django 5.2.2 on 2025-06-16 09:44

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Примерная стоимость бюджета')),
                ('is_displayed', models.BooleanField(default=True, verbose_name='Показать бюджет')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Бюджет на разработку',
                'verbose_name_plural': 'Бюджеты на разработку',
            },
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование вида услуги')),
                ('is_displayed', models.BooleanField(default=True, verbose_name='Показать вид услуги')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вид услуги',
                'verbose_name_plural': 'Виды услуг',
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя отправителя')),
                ('company', models.CharField(max_length=150, verbose_name='Компания или бренд')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Пример, +79510549236', max_length=128, null=True, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('comment', models.CharField(blank=True, default='', max_length=150, verbose_name='Комментарий')),
                ('file', models.FileField(null=True, upload_to='', verbose_name='Приложенный файл ТЗ')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.budget', verbose_name='Бюджет на разработку')),
                ('types_services', models.ManyToManyField(blank=True, related_name='types_services', to='Order.typeservice')),
            ],
            options={
                'verbose_name': 'Заказ услуги',
                'verbose_name_plural': 'Заказ услуг',
            },
        ),
    ]
